branches:
  only:
    - master

sudo: false

before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.27.zip
  - unzip -q google_appengine_1.9.27.zip

install:
  - pip install --upgrade pip
  - if [[ $TOXENV == 'py32' ]]; then pip install -I 'virtualenv<14.0'; fi
  - pip install tox-travis

script:
  - tox

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
