branches:
  only:
    - master
language: python
sudo: false
before_script:
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.27.zip
- unzip -q google_appengine_1.9.27.zip
install:
- pip install --upgrade pip
- if [[ $TOXENV == 'py32' ]]; then pip install -I 'virtualenv<14.0'; fi
- pip install tox
script:
- tox
python: 3.5
env:
  matrix:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=coveralls-py2
  - TOXENV=coveralls-py3
  - TOXENV=py27 APPENGINE_RUNTIME=python27
