language: python

cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
    - master
    - develop

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_script:
  - wget https://alg.li/algolia-keys && chmod +x algolia-keys

install:
  - pip install tox-travis

script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [[ ! "$TRAVIS_PULL_REQUEST_SLUG" =~ ^algolia\/ ]]; then eval $(./algolia-keys export) tox; else tox; fi
